import Head from "next/head";
import styles from "@/styles/Home.module.css";
import BootomBar from "./bottomBar";
import Section from "./section";
import Footer from "./footer";
import { FaPlus } from "react-icons/fa";
import { useState } from "react";
import { FaMinus } from "react-icons/fa";
import FooterMobile from './footerMobile';

export default function Home() {
  const [visibleA, setVisibleA] = useState(true);
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous"
        ></link>
        <link href="/static/styles/{name}.css" rel="stylesheet"></link>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
          crossorigin="anonymous"
        ></script>
      </Head>
      <div className="container-fluid px-0 ">
        <div className="row ">
          <div className="col">
            <BootomBar />
          </div>
        </div>
      </div>
      <div className={`${styles.mains} container px-0`}>
        <div className="row">
          <div className={`${styles.poster_mobile} col-12 col-md-12`}>
            <img
              src="https://www.plutos.one/images/contest/desk-Banner.png"
              alt="Description of the image"
              className={`${styles.poster} d-none d-md-block`}
            />
            <img
              src="https://www.plutos.one/images/contest/mob-Banner.png"
              alt="Description of the image"
              className={`${styles.poster} d-md-none`}
            />
          </div>
        </div>
        <div className={`${styles.contest} row`}>
          <div className="col-md-12">Valentine's Day Contest</div>
        </div>
        <div className={`${styles.outer_container}`}>
          <Section />
        </div>
      </div>
      <footer>
        <div
          className={`${styles.collapse_footer} d-md-none`}
          onClick={() => setVisibleA(!visibleA)}
        >
          
          <div>
            <img
              src="https://www.plutos.one/images/new-home/logos/plutos%20white%20logo.svg"
              alt=""
              className={`${styles.collapse_pluto_image}`}
            />
          </div>
          <div>
            {visibleA ? (
              <FaPlus className={`${styles.right_arrow_footer}`} size={10} />
            ) : (
              <FaMinus className={`${styles.right_arrow_footer}`} size={10} />
            )}
          </div>
        </div>
        {!visibleA && (
          <div className={`${styles.footer_container} d-md-none `}>
            <FooterMobile />
          </div>
        )}
        <div className={`${styles.footer_container} d-none d-md-block`}>
            <Footer />
          </div>
      </footer>
    </>
  );
}
